
[functions.analyze-object]
enabled = true
verify_jwt = false
import_map = "./functions/analyze-object/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/analyze-object/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/analyze-object/*.html" ]

[functions.remove-background]
verify_jwt = false

[functions.ocr-enhance]
verify_jwt = false
