/**
 * AI field badge — small inline pill showing AI provenance and confidence.
 *
 * Sits next to field labels where the value was generated by Gemini.
 * Confidence coloring: high (green 90-100), medium (amber 40-89), low (red <40).
 */
import React, { useMemo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useAppTranslation } from '../hooks/useAppTranslation';
import { radii, spacing, typography } from '../theme';
import type { ColorPalette } from '../theme';
import { useTheme } from '../theme/ThemeContext';

interface AIFieldBadgeProps {
  /**
   * Confidence as either a 0–100 integer or a 0–1 float. The component
   * auto-normalises: values <= 1 are multiplied by 100 before display, so
   * callers can pass either the Gemini raw JSON shape (0.95) or the
   * already-scaled form (95). Null / undefined renders nothing.
   */
  confidence?: number | null;
  visible: boolean;
}

/**
 * Normalize a confidence value to an integer 0–100.
 * - null/undefined/NaN → null (render nothing)
 * - value <= 1 → treated as 0–1 float, scaled to 0–100
 * - value > 1 → treated as already 0–100, clamped
 */
function normalizeConfidence(raw: number | null | undefined): number | null {
  if (raw == null || Number.isNaN(raw)) return null;
  if (raw <= 0) return 0;
  const scaled = raw <= 1 ? raw * 100 : raw;
  return Math.min(100, Math.round(scaled));
}

export function AIFieldBadge({ confidence, visible }: AIFieldBadgeProps) {
  const { t } = useAppTranslation();
  const { colors } = useTheme();
  const styles = useMemo(() => makeStyles(colors), [colors]);

  function confidenceColor(conf: number): string {
    if (conf >= 90) return colors.aiConfidenceHigh;
    if (conf >= 40) return colors.aiConfidenceMedium;
    return colors.aiConfidenceLow;
  }

  if (!visible) return null;

  const pct = normalizeConfidence(confidence);

  return (
    <View
      style={styles.pill}
      accessibilityRole="text"
      accessibilityLabel={t('aiBadge.aiSuggested')}
    >
      <Text style={styles.label}>{t('aiBadge.ai')}</Text>
      {pct != null && pct > 0 && (
        <Text
          style={[styles.confidence, { color: confidenceColor(pct) }]}
        >
          {pct}%
        </Text>
      )}
    </View>
  );
}

function makeStyles(c: ColorPalette) {
  return StyleSheet.create({
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: c.aiLight,
      borderRadius: radii.full,
      paddingHorizontal: spacing.sm,
      paddingVertical: 2,
      gap: spacing.xs,
    },
    label: {
      fontSize: typography.size.xs,
      fontWeight: typography.weight.semibold,
      color: c.ai,
    },
    confidence: {
      fontSize: typography.size.xs,
      fontWeight: typography.weight.medium,
    },
  });
}
