/**
 * AI field badge — small inline pill showing AI provenance and confidence.
 *
 * Sits next to field labels where the value was generated by Gemini.
 * Confidence coloring: high (green 90-100), medium (amber 40-89), low (red <40).
 */
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useAppTranslation } from '../hooks/useAppTranslation';
import { colors, radii, spacing, typography } from '../theme';

interface AIFieldBadgeProps {
  confidence?: number; // 0-100
  visible: boolean;
}

function confidenceColor(confidence: number): string {
  if (confidence >= 90) return colors.aiConfidenceHigh;
  if (confidence >= 40) return colors.aiConfidenceMedium;
  return colors.aiConfidenceLow;
}

export function AIFieldBadge({ confidence, visible }: AIFieldBadgeProps) {
  const { t } = useAppTranslation();

  if (!visible) return null;

  return (
    <View
      style={styles.pill}
      accessibilityRole="text"
      accessibilityLabel={t('aiBadge.aiSuggested')}
    >
      <Text style={styles.label}>{t('aiBadge.ai')}</Text>
      {confidence != null && confidence > 0 && (
        <Text
          style={[styles.confidence, { color: confidenceColor(confidence) }]}
        >
          {confidence}%
        </Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.aiLight,
    borderRadius: radii.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    gap: spacing.xs,
  },
  label: {
    fontSize: typography.size.xs,
    fontWeight: typography.weight.semibold,
    color: colors.ai,
  },
  confidence: {
    fontSize: typography.size.xs,
    fontWeight: typography.weight.medium,
  },
});
